# Generated by Django 5.1.6 on 2025-02-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100, null=True)),
                ('reason', models.CharField(max_length=100, null=True)),
                ('method', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=100, null=True)),
                ('created_date', models.CharField(max_length=100, null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank_Debit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100, null=True)),
                ('reason', models.CharField(max_length=100, null=True)),
                ('method', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=100, null=True)),
                ('created_date', models.CharField(max_length=100, null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
