# Generated by Django 5.1.6 on 2025-02-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bank_asset_bank_capital_bank_expense_bank_income_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100, null=True)),
                ('reason', models.CharField(max_length=100, null=True)),
                ('method', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=100, null=True)),
                ('created_date', models.CharField(max_length=100, null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100, null=True)),
                ('reason', models.CharField(max_length=100, null=True)),
                ('method', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=100, null=True)),
                ('created_date', models.CharField(max_length=100, null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Bank_Asset',
            new_name='Asset',
        ),
        migrations.RenameModel(
            old_name='Bank_Income',
            new_name='Capital',
        ),
        migrations.RenameModel(
            old_name='Bank_Purchase',
            new_name='Cash_Credit',
        ),
        migrations.RenameModel(
            old_name='Bank_Expense',
            new_name='Cash_Debit',
        ),
        migrations.RenameModel(
            old_name='Bank_Liability',
            new_name='Expense',
        ),
        migrations.RenameModel(
            old_name='Bank_Capital',
            new_name='Income',
        ),
    ]
