# Generated by Django 5.1.6 on 2025-02-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_liability_purchase_rename_bank_asset_asset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_credit',
            name='method',
        ),
        migrations.RemoveField(
            model_name='bank_debit',
            name='method',
        ),
        migrations.RemoveField(
            model_name='cash_credit',
            name='method',
        ),
        migrations.RemoveField(
            model_name='cash_debit',
            name='method',
        ),
    ]
