# Generated by Django 5.1.6 on 2025-02-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_bank_credit_method_remove_bank_debit_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='decrease',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
