# Generated by Django 5.1.6 on 2025-03-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_asset_decrease'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Liability',
            new_name='Loan',
        ),
    ]
